### ISSUE TITLE
Call to getChildElements() makes the iteration skip steps 

### ISSUE THREAD

**Issue by greg0ire** [hakre/XMLReaderIterator#3]
I'm trying to read an xml file created with `mysqldump --xml`

The code looks like this :

``` php
<?php

        $reader = new \XMLReader();
        $reader->open($this->filename);
        $objects = new \XMLElementIterator($reader, 'row');

        foreach ($objects as $key => $row) {
            echo 'importing row #' . ($key + 1) . PHP_EOL;

            $this->importRow($row, $manager);
        }

```

The importRow method loops over fields. It looks like this :

``` php
        foreach ($row->getChildElements() as $field) {
            $this->setValue(
                $entity,
                $field->getAttribute('name'),
                (string) $field
            );
        }
```

When I comment out the `importRow()` call I get the right number of iterations. When I do not, I get half, and only entities with even ids get imported. It is as if the `getChildElements()` call would make the pointer increase.

Am I using the library wrong ?

**Comment by jwundrak** [comment]
@hakre, this issue can be closed, because it was resolved by 0.1.11 with `skipNextRead`-method and without this method in PR #21

**Comment by dearsina** [comment]
@jwundrak Can you please show me an example of how you can iterate over child (or grand child) nodes without it skipping the parent nodes using `skipNextRead`? Because I think this issue is still prevalent.
